/**
 * One-off (Aug 2026): fill missing phone/email on "Agile Lead Task" rows from
 * the BLP Super-CRM (exact unique name match only). Never overwrites data;
 * skips junk-looking CRM emails (phone-as-email, autogenerated placeholders).
 * Run: npx tsx --env-file=.env.local scripts/enrich-agile-from-crm.ts
 */
import { createRequire } from "module";
import { getLeads, updateLeadFields, ensureAppColumns } from "../src/lib/leads";

const require2 = createRequire(import.meta.url);
// eslint-disable-next-line @typescript-eslint/no-require-imports
const Database = require2("/Users/ivorylarson/blp-crm/node_modules/better-sqlite3");

const norm = (s: string) => (s || "").toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9]+/g, " ").trim();
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

function firstPhone(raw: string): string {
  try {
    const arr = JSON.parse(raw || "[]") as string[];
    for (const p of arr) {
      const d = String(p).replace(/\D/g, "");
      if (d.length >= 10) return String(p);
    }
  } catch { /* not json */ }
  return "";
}

function firstRealEmail(raw: string): string {
  try {
    const arr = JSON.parse(raw || "[]") as string[];
    for (const e of arr) {
      const s = String(e).trim().toLowerCase();
      if (!/@/.test(s)) continue;
      const local = s.split("@")[0];
      if (/^\d{3}[-.]?\d{3}[-.]?\d{4}$/.test(local)) continue; // phone-as-email junk
      if (/\d{5,}$/.test(local)) continue; // autogenerated placeholder junk
      return s;
    }
  } catch { /* not json */ }
  return "";
}

async function main() {
  const db = new Database("/Users/ivorylarson/blp-crm/data/blp-crm.db", { readonly: true });
  const clients = db.prepare("SELECT id, display_name, emails, phones FROM clients").all() as {
    id: number; display_name: string; emails: string; phones: string;
  }[];
  const byName = new Map<string, typeof clients>();
  for (const c of clients) {
    const n = norm(c.display_name);
    if (n.length >= 5) byName.set(n, [...(byName.get(n) || []), c]);
  }

  const { leads, shape } = await getLeads(true);
  const s = await ensureAppColumns(shape);
  const agile = leads.filter(
    (l) =>
      (l.leadType || "").trim().toLowerCase() === "agile lead task" &&
      !(l.status || "").toLowerCase().includes("duplicate")
  );

  let enriched = 0;
  for (const a of agile) {
    const matches = byName.get(norm(a.name)) || [];
    if (matches.length !== 1) continue; // unique-match only
    const c = matches[0];
    const fields: Record<string, string> = {};
    if (!a.phone.trim()) {
      const p = firstPhone(c.phones);
      if (p) fields.phone = p;
    }
    if (!a.emailClean.trim()) {
      const e = firstRealEmail(c.emails);
      if (e) fields.email = e;
    }
    if (!Object.keys(fields).length) continue;
    await updateLeadFields(a, s, fields);
    enriched++;
    console.log(`${a.name} (${a.id}): +${Object.entries(fields).map(([k, v]) => `${k}=${v}`).join(", ")}`);
    await sleep(1100);
  }
  console.log(`\nDone. Enriched ${enriched} Agile rows from the CRM.`);
}
main().catch((e) => {
  console.error(e);
  process.exit(1);
});
